### ISSUE TITLE
vscode-ansible: outdated plugin

### ISSUE THREAD

**Issue by dwcaesar** [Zuehlke/linux-developer-vm-with-ansible#25]
It is no longer possible to build a vm from scratch, as a vscode plugin is no longer available.

The plugin [zbr.vscode-ansible](https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible) has been pulled from the marketplace.
Instead you should use [redhat.ansible](https://marketplace.visualstudio.com/items?itemName=redhat.ansible).

**Comment by tknerr** [comment]
Hey @dwcaesar, sorry for the late reply, I just noticed this issue now.

Actually, I was not aware, but @mexmirror was, and so this has been fixed via #24 just recently :)

Thanks again (both for reporting, as well as for fixing it)! 👍🏻 :)
