### ISSUE TITLE
What is the license of this repo?

### ISSUE THREAD

**Issue by zuehlke-hach** [Zuehlke/linux-developer-vm-with-ansible#3]
What is the license of the code in this repository?
I propose https://unlicense.org/ .

**Comment by tknerr** [comment]
Hi @zuehlke-hach , sorry for the late reply. I think I added the MIT license at some point in time, as this is what I mostly used so far. https://unlicense.org/ looks interesting though, and I will consider it for my next project :) 👍🏻
